# Generated by Django 4.2.6 on 2024-04-08 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0560_systemsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentChatTopic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=1024)),
                ("index", models.IntegerField()),
                ("created_at", models.DateTimeField(verbose_name="date sent")),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.stream"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentChatTopicSub",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("index", models.IntegerField()),
                ("sub_topic_subject", models.TextField()),
                ("topic_state", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(verbose_name="date sent")),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.agentchattopic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentChatTopicChatHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("index", models.IntegerField()),
                ("role", models.CharField(max_length=1024)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(verbose_name="date sent")),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.agentchattopicsub"
                    ),
                ),
            ],
        ),
    ]
