# Generated by Django 4.2.6 on 2024-05-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0561_agentchattopic_agentchattopicsub_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageLanguage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Catalan", "Spain"),
                            ("Slovenian", "Slovenia"),
                            ("Maltese", "Malta"),
                            ("Lithuanian", "Lithuania"),
                            ("Dogri", "India"),
                            ("Haryanvi", "India"),
                            ("Marwari", "India"),
                            ("Slovak", "Slovakia"),
                            ("Welsh", "Wales"),
                            ("Mongolian", "Mongolia"),
                            ("Awadhi", "India"),
                            ("Romanian", "Romania"),
                            ("MandarinChinese", "China"),
                            ("Cantonese(Yue)", "China"),
                            ("Irish", "Ireland"),
                            ("Moldovan", "Moldova"),
                            ("Czech", "CzechRepublic"),
                            ("Gujarati", "India"),
                            ("", ""),
                            ("Japanese", "Japan"),
                            ("Punjabi", "India"),
                            ("Vietnamese", "Vietnam"),
                            ("Kashmiri", "India"),
                            ("Faroese", "FaroeIslands"),
                            ("Danish", "Denmark"),
                            ("Azerbaijani", "Azerbaijan"),
                            ("Portuguese", "Portugal"),
                            ("Mandarin", "China"),
                            ("Kyrgyz", "Kyrgyzstan"),
                            ("Marathi", "India"),
                            ("Uzbek", "Uzbekistan"),
                            ("Norwegian", "Norway"),
                            ("Bosnian", "BosniaandHerzegovina"),
                            ("Latvian", "Latvia"),
                            ("Greek", "Greece"),
                            ("Oriya", "India"),
                            ("Galician", "Spain"),
                            ("Indonesian", "Indonesia"),
                            ("Dutch", "Netherlands"),
                            ("Croatian", "Croatia"),
                            ("Chinese", "China"),
                            ("Korean", "SouthKorea"),
                            ("Kannada", "India"),
                            ("Bhojpuri", "India"),
                            ("Konkani", "India"),
                            ("Armenian", "Armenia"),
                            ("Sinhala", "SriLanka"),
                            ("Bashkir", "Russia"),
                            ("Hungarian", "Hungary"),
                            ("Nepali", "Nepal"),
                            ("Kazakh", "Kazakhstan"),
                            ("Albanian", "Albania"),
                            ("Slovene", "Slovenia"),
                            ("French", "France"),
                            ("German", "Germany"),
                            ("Pashto", "Afghanistan"),
                            ("Ukrainian", "Ukraine"),
                            ("Malay", "Malaysia"),
                            ("Rajasthani", "India"),
                            ("Hindi", "India"),
                            ("Russian", "Russia"),
                            ("Serbian", "Serbia"),
                            ("Georgian", "Georgia"),
                            ("Persian(Farsi)", "Iran"),
                            ("Macedonian", "NorthMacedonia"),
                            ("Wu", "China"),
                            ("Polish", "Poland"),
                            ("Bengali", "Bangladesh"),
                            ("BrazilianPortuguese", "Brazil"),
                            ("Arabic", "ArabWorld"),
                            ("Montenegrin", "Montenegro"),
                            ("Santali", "India"),
                            ("MinNan", "China"),
                            ("Basque", "Spain"),
                            ("Bulgarian", "Bulgaria"),
                            ("English", "UnitedKingdom"),
                            ("Finnish", "Finland"),
                            ("Maithili", "India"),
                            ("Urdu", "Pakistan"),
                            ("Estonian", "Estonia"),
                            ("Chhattisgarhi", "India"),
                            ("Italian", "Italy"),
                            ("Sindhi", "Pakistan"),
                            ("Belarusian", "Belarus"),
                            ("Sanskrit", "India"),
                            ("Javanese", "Indonesia"),
                        ],
                        default="Vietnamese",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("rendered_content", models.TextField(null=True)),
                ("rendered_content_version", models.IntegerField(null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.message"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["message"], name="zerver_message_language_message_idx")
                ],
                "unique_together": {("message", "language")},
            },
        ),
    ]
