# Generated by Django 4.2.6 on 2024-06-08 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0562_messagelanguage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("external_id", models.CharField(max_length=1024)),
                ("job_type", models.CharField(max_length=1024)),
                ("assistant_id", models.CharField(max_length=1024, null=True)),
                ("state", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(verbose_name="created at")),
            ],
        ),
        migrations.CreateModel(
            name="AssistantJobOutput",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("output_type", models.CharField(max_length=1024)),
                ("output_name", models.CharField(max_length=1024)),
                ("output_value", models.TextField()),
                ("order", models.IntegerField()),
                ("created_at", models.DateTimeField(verbose_name="created at")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.assistantjob"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssistantJobInput",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("input_type", models.CharField(max_length=1024)),
                ("input_name", models.CharField(max_length=1024)),
                ("input_value", models.TextField()),
                ("order", models.IntegerField()),
                ("created_at", models.DateTimeField(verbose_name="created at")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.assistantjob"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssistantJobChatHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("index", models.IntegerField()),
                ("role", models.CharField(max_length=1024)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(verbose_name="date sent")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.assistantjob"
                    ),
                ),
            ],
        ),
    ]
