# Generated by Django 4.2.6 on 2024-06-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0563_assistantjob_assistantjoboutput_assistantjobinput_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="assistant_type",
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
    ]
