# Generated by Django 4.2.6 on 2024-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0565_evaluation_evaluationassistantjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="external_stream_type",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
