# Generated by Django 4.2.6 on 2024-07-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0566_stream_external_stream_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentchathistory",
            name="bot",
            field=models.CharField(default="ai", max_length=1024),
        ),
    ]
