# Generated by Django 5.0.6 on 2024-10-28 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0568_alter_agentchathistory_id_alter_evaluation_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealmMetadata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=1024)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(verbose_name="created at")),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
    ]
