# Generated by Django 5.0.6 on 2024-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0569_realmmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentchathistory",
            name="assistant_id",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
